apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: gemcloud-system/gems-controller-cert
  labels:
    app.kubernetes.io/name: gems-controller-manager
    control-plane: controller-manager
  name: gems-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /mutate
  failurePolicy: Fail
  name: mutate.resourcequota.dev
  rules:
  - apiGroups:
    - gems.kubegems.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenantresourcequotas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /mutate
  failurePolicy: Fail
  name: mutate.environment.dev
  rules:
  - apiGroups:
    - gems.kubegems.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - environments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /mutate
  failurePolicy: Fail
  name: mutate.gateway.dev
  rules:
  - apiGroups:
    - gems.kubegems.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenantgateways
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /mutate
  failurePolicy: Fail
  name: mutate.ingress.dev
  rules:
  - apiGroups:
    - extensions
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /label-injector
  failurePolicy: Ignore
  name: mutate.label-injector.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - configmaps
    - secrets
    - services
    - daemonsets
    - deployments
    - statefulsets
    - jobs
    - cronjobs
    - persistentvolumeclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: gems-webhook-service
      namespace: gemcloud-system
      path: /label-injector
  failurePolicy: Ignore
  name: mutate.label-injector-logging.dev
  rules:
  - apiGroups:
    - logging.banzaicloud.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
    - outputs
  sideEffects: None
