- name: Core Plugins | Kube State Metrics 
  community.kubernetes.k8s:
    state: '{{"present" if core_plugins.kube_state_metrics.enabled else "absent"}}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - kube-state-metrics/sa.yaml
    - kube-state-metrics/psp.yaml
    - kube-state-metrics/clusterrole.yaml
    - kube-state-metrics/clusterrolebinding.yaml
    - kube-state-metrics/clusterrole-psp.yaml
    - kube-state-metrics/clusterrolebinding-psp.yaml
    - kube-state-metrics/deploy.yaml
    - kube-state-metrics/service.yaml