- name: Kubernetes Plugins | Grafana Operator | CRDs
  community.kubernetes.k8s:
    state: present 
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - grafana/operator/crds/grafanadashboards.yaml
    - grafana/operator/crds/grafanadatasources.yaml
    - grafana/operator/crds/grafanas.yaml

- name: Kubernetes Plugins | Grafana Operator 
  community.kubernetes.k8s:
    state: '{{"present" if kubernetes_plugins.grafana.enabled else "absent"}}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - grafana/operator/sa.yaml
    - grafana/operator/role.yaml
    - grafana/operator/rolebinding.yaml
    - grafana/operator/clusterrole.yaml
    - grafana/operator/clusterrolebinding.yaml
    - grafana/operator/secret.yaml
    - grafana/operator/operator.yaml

- name: Kubernetes Plugins | Grafana
  community.kubernetes.k8s:
    state: '{{"present" if kubernetes_plugins.grafana.enabled else "absent"}}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  ignore_errors: true
  with_items:
    - grafana/grafana.yaml

- name: Kubernetes Plugins | Grafana | Grafana Datasource Prometheus
  when: 
    - kubernetes_plugins.grafana.enabled
  community.kubernetes.k8s:
    state: '{{"present" if core_plugins.monitoring.operator.prometheus is defined and core_plugins.monitoring.operator.prometheus.enabled else "absent"}}'
    definition: "{{ lookup('file', item) | from_yaml }}"
  ignore_errors: true
  with_items:
    - grafana/datasource/prometheus.yaml

- name: Kubernetes Plugins | Grafana | Grafana Datasource Loki
  community.kubernetes.k8s:
    state: '{{"present" if core_plugins.logging.operator.loki is defined and core_plugins.logging.operator.loki.enabled else "absent"}}'
    definition: "{{ lookup('file', item) | from_yaml }}"
  ignore_errors: true
  with_items:
    - grafana/datasource/loki.yaml

- name: Kubernetes Plugins | Grafana | Grafana Dashboard
  community.kubernetes.k8s:
    state: '{{"present" if kubernetes_plugins.grafana.enabled else "absent"}}'
    definition: "{{ lookup('file', item) | from_yaml }}"
  ignore_errors: true
  with_items:
    - grafana/dashboard/kubernetes-api.yaml  
    - grafana/dashboard/node.yaml  
    - grafana/dashboard/argocd.yaml  
    - grafana/dashboard/loki.yaml  
    - grafana/dashboard/loki-redis.yaml  