#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gems-gitea
  name: gems-gitea
  namespace: gemcloud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gems-gitea
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gems-gitea
    spec:
      initContainers:
        - name: init-directories
          image: "{{ global.repository | default('docker.io/kubegems')}}/gitea:1.14.6"
          imagePullPolicy: IfNotPresent
          command: ["/usr/sbin/init_directory_structure.sh"]
          env:
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_TEMP
              value: /tmp/gitea
          volumeMounts:
            - name: init
              mountPath: /usr/sbin
            - name: temp
              mountPath: /tmp
            - name: config
              mountPath: /etc/gitea/conf
            - name: data
              mountPath: /data
        - name: configure-gitea
          image: "{{ global.repository | default('docker.io/kubegems')}}/gitea:1.14.6"
          imagePullPolicy: IfNotPresent
          command: ["/usr/sbin/configure_gitea.sh"]
          securityContext:
            runAsUser: 1000
          env:
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: GITEA_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: gitea-root-user
                  name: gems-secret
            - name: GITEA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: gitea-root-password
                  name: gems-secret
          volumeMounts:
            - name: init
              mountPath: /usr/sbin
            - name: temp
              mountPath: /tmp
            - name: data
              mountPath: /data
      containers:
        - name: gitea
          image: "{{ global.repository | default('docker.io/kubegems')}}/gitea:1.14.6"
          imagePullPolicy: IfNotPresent
          env:
            - name: SSH_LISTEN_PORT
              value: "22"
            - name: SSH_PORT
              value: "22"
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: TMPDIR
              value: /tmp/gitea
          ports:
            - name: tcp-22
              containerPort: 22
            - name: tcp-3000
              containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: tcp-3000
            initialDelaySeconds: 200
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: tcp-3000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: temp
              mountPath: /tmp
            - name: data
              mountPath: /data
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
      - name: {{ global.imagepullsecret | default('kubegems') }}
      {% endif %}
      restartPolicy: Always
      volumes:
      - name: init
        secret:
          secretName: gems-gitea-init
          defaultMode: 0777
      - name: config
        secret:
          secretName: gems-gitea
      - name: temp
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: gems-gitea-data